### PR TITLE
chore(deps): bump prisma from v2 to v3

### LINKED ISSUE #38: Support Prisma v3
Prisma has been upgrade to v3. It would be great to bump the versions of peer dependencies.

### PR DESCRIPTION
**Pull request by zillding**
close #38

### CODE REVIEW

**Comment by hsluoyz** [comment]
@zillding package-lock.json ?

**Comment by hsluoyz** [comment]
@zillding fix:

image

**Comment by zillding** [comment]
@hsluoyz package-lock.json is updated together with package.json since the dev dependencies are also updated. Is that okay?

**Comment by zillding** [comment]
can we release this change to npm? thanks. 🙏

**Comment by hsluoyz** [comment]
@zillding we used `semantic-release`, which does auto-release based on the prefix. But you used `chore(deps)` prefix, which doesn't trigger new version. You have to make a new PR with "feat:" or "fix:" prefix to trigger a new version.

**Comment by zillding** [comment]
@hsluoyz thanks for the reply. then in this case, what do you suggest we should do in order to release this? not sure if this would count as a 'feat' or 'fix'.

**Comment by hsluoyz** [comment]
@zillding you can make a new PR to do things like: improve the README.md, add some comments to the code, fix some typos in the English texts, etc. Then use the "fix:" prefix.

**Pull request merged**
