### PR TITLE
fix: remove @prisma/cli dependency

### PR DESCRIPTION
**Pull request by Zxilly**
Closes https://github.com/node-casbin/prisma-adapter/issues/22

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Zxilly what does this PR do?

**Comment by Zxilly** [comment]
@hsluoyz `@prisma/cli` has been abandoned by prisma community. It was renamed to `prisma`.
Seems it also has some side affect which broke CI. I'm working on this.

**Comment by hsluoyz** [comment]
@Jack-Barry please review.

**Comment by Zxilly** [comment]
@nshusr plz review this.

**Comment by Jack-Barry** [comment]
Added some notes for my review of this in the original issue

**Pull request merged**
